const KEY='parfum-wardrobe-v19';
const DEFAULT={scores:{},core:[3,18,2,5,10,1,6,8,4],roles:{3:'Signature · Office · Alltag',18:'Date · elegant · Abend',2:'Winter · Abend · cozy',5:'Date · Oud/Rose · besonderer Abend',10:'Herbst · Leder · Abend',1:'Sommer · Freizeit · Date',6:'Statement · Freizeit · Date',8:'Sport · Hitze · Sommer',4:'Office · Alltag · warmer Tag'},out:[15]};
let tab='ranking',filter='all',query='';
function cloneDefault(){return JSON.parse(JSON.stringify(DEFAULT))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...cloneDefault(),...x,scores:{...(x.scores||{})},roles:{...DEFAULT.roles,...(x.roles||{})}}}catch{return cloneDefault()}}
let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));const e=document.getElementById('saved');if(e)e.textContent='gespeichert '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});toast('Gespeichert')}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.classList.remove('show'),1200)}
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m))}
function score(x){return Object.prototype.hasOwnProperty.call(state.scores,String(x.id))?state.scores[String(x.id)]:x.score}
function sorted(){return [...PERFUMES].sort((a,b)=>(score(b)??-1)-(score(a)??-1)||a.name.localeCompare(b.name,'de'))}
function isCore(id){return state.core.includes(id)}
function status(x){if(state.out.includes(x.id))return 'RAUS';const s=score(x);if(s===null)return 'OFFEN';if(s>=7.5)return 'BEHALTEN';if(s<6)return 'RAUS';return 'PRÜFEN'}
function role(x){return state.roles[String(x.id)]||x.use||'—'}
function ranking(){const all=sorted();const list=all.filter(x=>{const hay=(x.name+' '+x.brand).toLowerCase();if(query&&!hay.includes(query))return false;if(filter==='core'&&!isCore(x.id))return false;if(filter==='open'&&score(x)!==null)return false;if(filter==='out'&&status(x)!=='RAUS')return false;if(['G1','G2','G3'].includes(filter)&&x.group!==filter)return false;return true});return `<div class="toolbar"><input id="search" class="search" placeholder="Duft oder Marke suchen …" value="${esc(query)}"><div class="chips">${[['all','Alle'],['core','Core'],['open','Offen'],['G1','G1'],['G2','G2'],['G3','G3'],['out','Raus']].map(a=>`<button class="chip ${filter===a[0]?'on':''}" data-filter="${a[0]}">${a[1]}</button>`).join('')}</div></div><div class="list">${list.map(x=>{const r=all.indexOf(x)+1,s=status(x);return `<article class="card"><div class="main"><div class="rank">${r}</div><div><div class="name">${esc(x.name)}</div><div class="brand">${esc(x.brand)}</div><div class="meta"><span class="pill">${x.group}</span>${x.price?`<span class="pill">ca. ${x.price} €</span>`:''}${isCore(x.id)?'<span class="pill core">CORE</span>':''}${s==='RAUS'?'<span class="pill out">RAUS</span>':s==='BEHALTEN'?'<span class="pill keep">BEHALTEN</span>':''}</div></div><input class="score" inputmode="decimal" data-score="${x.id}" value="${score(x)??''}" placeholder="—"><button class="star ${isCore(x.id)?'on':''}" data-core="${x.id}">★</button></div><details class="details"><summary>Details · Verwendung · Link</summary><div class="detailgrid"><div class="box"><b>V11 / Einsatz</b>${esc(x.use||'—')}</div><div class="box"><b>Status</b>${s}</div></div>${isCore(x.id)?`<input class="role" data-role="${x.id}" value="${esc(role(x))}">`:''}<br><a class="link" href="${esc(x.url)}" target="_blank" rel="noopener">Parfumo ↗</a></details></article>`}).join('')||'<div class="empty">Keine Treffer.</div>'}</div>`}
function coreView(){const items=state.core.map(id=>PERFUMES.find(x=>x.id===id)).filter(Boolean);return `<div class="sectionHead"><h2>Working Core</h2><span>nicht final · Sterne ändern die Auswahl</span></div><div class="coregrid">${items.map(x=>`<article class="corecard"><h3>${esc(x.name)}</h3><p>${esc(x.brand)} · ${x.group} · ${score(x)??'offen'}/10</p><input class="role" data-role="${x.id}" value="${esc(role(x))}"><a class="link" href="${esc(x.url)}" target="_blank" rel="noopener">Parfumo ↗</a><button class="star on" style="margin-left:6px" data-core="${x.id}">★</button></article>`).join('')}</div>`}
function groups(){const all=sorted();return `<div class="sectionHead"><h2>Gruppen 1–3</h2><span>Zuordnung nach V11</span></div>${['G1','G2','G3'].map(g=>{const desc=g==='G1'?'warm · süß · cremig':g==='G2'?'dunkel · würzig · Leder/Oud':'frisch · zitrisch · clean';const a=all.filter(x=>x.group===g);return `<section class="group"><div class="groupHead"><b>${g}</b><span>${desc} · ${a.length} Düfte</span></div><div class="groupRows">${a.map(x=>`<div class="grow"><div class="grank">${all.indexOf(x)+1}</div><div><div class="gname">${esc(x.name)}${isCore(x.id)?' ★':''}</div><div class="gbrand">${esc(x.brand)} · ${esc(x.use||'—')}</div></div><div class="gscore">${score(x)??'—'}</div></div>`).join('')}</div></section>`}).join('')}`}
function avg(g){const a=PERFUMES.filter(x=>x.group===g).map(score).filter(x=>typeof x==='number');return a.length?(a.reduce((p,c)=>p+c,0)/a.length).toFixed(1).replace('.',','):'—'}
function profile(){return `<div class="profile"><h2>Dein Duftprofil</h2><p>Deine Sammlung hat zwei starke Pole: klare, hochwertige Frische für Office, Alltag und Sommer sowie dunklere, warme Statement-Düfte mit Vanille, Leder, Oud und würziger Tiefe. G3 ist die verlässlichste Alltagsbasis, G2 liefert Charakter und Abendwirkung, G1 bleibt selektiver.</p><div class="stats"><div class="stat"><b>${avg('G1')}</b><small>G1 Durchschnitt</small></div><div class="stat"><b>${avg('G2')}</b><small>G2 Durchschnitt</small></div><div class="stat"><b>${avg('G3')}</b><small>G3 Durchschnitt</small></div></div></div><div style="margin-top:14px">${coreView()}</div>`}
function backup(){return `<div class="sectionHead"><h2>Backup</h2><span>für Gerätewechsel oder Sicherheit</span></div><div class="profile"><h2>Deine Daten bleiben bei dir</h2><p>Bewertungen, Core-Auswahl und Rollen werden lokal in Safari gespeichert. Exportiere gelegentlich ein JSON-Backup und importiere es bei Bedarf wieder.</p></div><div class="actions"><button id="exportJson" class="action">JSON exportieren</button><button id="importJson" class="action">JSON importieren</button><button id="exportCsv" class="action">CSV exportieren</button><button id="reset" class="action">Auf Standard zurücksetzen</button></div>`}
function render(){const v=document.getElementById('view');if(!v)return;v.innerHTML=tab==='ranking'?ranking():tab==='core'?coreView():tab==='groups'?groups():tab==='profile'?profile():backup();bind()}
function bind(){document.getElementById('search')?.addEventListener('input',e=>{query=e.target.value.toLowerCase();render()});document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>{filter=e.dataset.filter;render()});document.querySelectorAll('[data-score]').forEach(e=>e.onchange=()=>{const raw=e.value.trim().replace(',','.');state.scores[e.dataset.score]=raw===''?null:Math.max(0,Math.min(10,Number(raw)));save();render()});document.querySelectorAll('[data-core]').forEach(e=>e.onclick=()=>{const id=Number(e.dataset.core);state.core=isCore(id)?state.core.filter(x=>x!==id):[...state.core,id];save();render()});document.querySelectorAll('[data-role]').forEach(e=>e.onchange=()=>{state.roles[e.dataset.role]=e.value;save()});document.getElementById('exportJson')?.addEventListener('click',exportJson);document.getElementById('importJson')?.addEventListener('click',()=>document.getElementById('importFile').click());document.getElementById('exportCsv')?.addEventListener('click',exportCsv);document.getElementById('reset')?.addEventListener('click',()=>{if(confirm('Bewertungen und Core wirklich auf Standard zurücksetzen?')){localStorage.removeItem(KEY);state=load();render();save()}})}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function exportJson(){download('Parfum_Wardrobe_Backup.json',JSON.stringify(state,null,2),'application/json');toast('Backup erstellt')}
function exportCsv(){const rows=[['Rang','Duft','Marke','Bewertung','Gruppe','Core','Status','Preis']];const all=sorted();all.forEach((x,i)=>rows.push([i+1,x.name,x.brand,score(x)??'',x.group,isCore(x.id)?'Ja':'Nein',status(x),x.price??'']));download('Parfum_Wardrobe.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),'text/csv');toast('CSV erstellt')}
document.getElementById('importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);state={...cloneDefault(),...x,roles:{...DEFAULT.roles,...(x.roles||{})}};save();render();toast('Backup importiert')}catch{alert('Backup konnte nicht gelesen werden.')}};r.readAsText(f)});
document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));e.classList.add('active');tab=e.dataset.tab;window.scrollTo({top:0,behavior:'smooth'});render()});
document.getElementById('closeInstall').onclick=()=>document.getElementById('install').classList.add('hidden');
const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;if(standalone)document.getElementById('install').classList.add('hidden');
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
render();
